ansible-collections/community.dns

- changelogs/fragments/13-alabel-confusion.yml
- plugins/module_utils/names.py
- tests/unit/plugins/module_utils/test_names.py
Some valid ASCII labels were converted to alabels.
plugins/module_utils/names.py
> Fix label normalization problem

- docs/docsite/extra-docs.yml
- docs/docsite/rst/filter_guide.rst
- docs/docsite/rst/hosttech_guide.rst
This adds scenario guides to this collection. This PR depends on ansible-community/antsibull#255.
The result of how this looks can be seen here:
- https://ansible.fontein.de/collections/community/dns/ (note the new subtitle 'Guides')
- https://ansible.fontein.de/collections/community/dns/docsite/filter_guide.html
- https://ansible.fontein.de/collections/community/dns/docsite/hosttech_guide.html
scenario guide
> Add scenario guides

- changelogs/fragments/ansible-core-_text.yml
- plugins/module_utils/hosttech/json_api.py
- plugins/module_utils/hosttech/wsdl_api.py
- plugins/module_utils/names.py
- plugins/module_utils/resolver.py
- plugins/module_utils/wsdl.py
- plugins/modules/wait_for_txt.py
While the private API `ansible.module_utils._text` was the default place to get `to_text`, `to_bytes` and `to_native` for a long time, at least since Ansible 2.9 there's a non-private alternative: `ansible.module_utils.common.text.converters`. So let's use it :)
various plugins
> Replace ansible.module_utils._text by ansible.module_utils.common.text.converters

- changelogs/fragments/38-zone-extra-info.yml
- plugins/module_utils/hetzner/api.py
- plugins/module_utils/hosttech/json_api.py
- plugins/module_utils/hosttech/wsdl_api.py
- plugins/module_utils/module/zone_info.py
- plugins/module_utils/zone.py
- plugins/modules/hetzner_dns_zone_info.py
- plugins/modules/hosttech_dns_zone_info.py
- tests/unit/plugins/module_utils/test_zone.py
- tests/unit/plugins/modules/hosttech.py
- tests/unit/plugins/modules/test_hetzner_dns_zone_info.py
- tests/unit/plugins/modules/test_hosttech_dns_zone_info.py
The `*_dns_zone_info` modules should return more information that the APIs provide.
hetzner_dns_zone_info
hosttech_dns_zone_info
> Add more zone information

- changelogs/fragments/56-tests-fixes.yml
- plugins/module_utils/hosttech/json_api.py
- tests/integration/targets/hetzner/tasks/record-sets.yml
- tests/unit/plugins/modules/hosttech.py
- tests/unit/plugins/modules/test_hosttech_dns_zone_info.py
While trying out the integration tests for the HostTech and Hetzner modules, I found some problems:
1. The Hetzner tests weren't adapted to no default TTL;
2. The HostTech tests showed that the hosttech_dns_zone_info module returns less information when run for a zone name than for a zone ID. (The zone list API call returns less information than the zone GET API call for DNSSEC enabled domains.)
hosttech_dns_zone_info
Hetzner integration tests
> Integration test fixes, make sure that hosttech_dns_zone_info always returns same info

- changelogs/fragments/58-hetzner-api-errors.yml
- plugins/module_utils/hetzner/api.py
- plugins/module_utils/json_api_helper.py
- tests/unit/plugins/modules/test_hetzner_dns_record_set.py
- tests/unit/plugins/modules/test_hetzner_dns_record_sets.py
- tests/unit/plugins/modules/test_hosttech_dns_record_set.py
- tests/unit/plugins/modules/test_hosttech_dns_record_sets.py
While working on #57 I got some Internal Server Errors which disguided as HTTP status code 200, which means OK.
plugins/module_utils/hetzner/api.py
> Handle API errors for Hetzner's API that don't come with HTTP error status codes

- docs/docsite/rst/hetzner_guide.rst
- docs/docsite/rst/hosttech_guide.rst
The migration guide uses a wrong module name, and the guides don't mention `txt_transformation`.
scenario guides
> Improve docs

- changelogs/fragments/57-60-txt_transformation.yml
- plugins/doc_fragments/options.py
- plugins/inventory/hetzner_dns_records.py
- plugins/inventory/hosttech_dns_records.py
- plugins/module_utils/module/record.py
- plugins/module_utils/module/record_set.py
- plugins/module_utils/module/record_set_info.py
- plugins/module_utils/module/record_sets.py
- plugins/module_utils/options.py
- plugins/modules/hetzner_dns_record.py
- plugins/modules/hetzner_dns_record_set.py
- plugins/modules/hetzner_dns_record_set_info.py
- plugins/modules/hetzner_dns_record_sets.py
- plugins/modules/hosttech_dns_record.py
- plugins/modules/hosttech_dns_record_set.py
- plugins/modules/hosttech_dns_record_set_info.py
- plugins/modules/hosttech_dns_record_sets.py
- plugins/plugin_utils/inventory/records.py
- tests/unit/plugins/inventory/test_hetzner_dns_records.py
While this should not really be needed in the inventory plugin, I think it's still better to implement transformations there as well in case someone really wants to create hosts from TXT entries. (and possibly when we add other transformations in the future, then the infrastructure is already there...)
Follow-up to #57.
> Improving handling of TXT values: forgot changelog fragment and inventory plugin

- changelogs/fragments/63-records-extra-info.yml
- plugins/module_utils/hetzner/api.py
- plugins/module_utils/hosttech/json_api.py
- plugins/module_utils/hosttech/wsdl_api.py
- plugins/module_utils/module/record.py
- plugins/module_utils/module/record_set.py
- plugins/module_utils/module/record_sets.py
- plugins/module_utils/record.py
- plugins/module_utils/zone_record_helpers.py
- tests/unit/plugins/module_utils/hosttech/test_json_api.py
- tests/unit/plugins/module_utils/test_record.py
- tests/unit/plugins/module_utils/test_zone.py
- tests/unit/plugins/modules/test_hetzner_dns_record.py
- tests/unit/plugins/modules/test_hosttech_dns_record.py
Background: https://github.com/markuman/hetzner_dns/issues/6#issuecomment-914481052
Right now this only affects diff mode for *_dns_record, since the diff mode for *_dns_record_set and *_dns_record_sets aggregates multiple records, where including the extra only works well if we know how to aggregate its contents.
I'm currently thinking of adding a *_dns_record_info module to retrieve individual records (and not record sets).
DNS record API
*_dns_record
> Provide access to extra record info

- changelogs/fragments/65-wait_for_txt-ns.yml
- plugins/module_utils/resolver.py
Apparently on systems using systemd-resolvd (like Ubuntu 20.04), the code to find nameservers resulted in an empty list. This caused wait_for_txt to exit directly without waiting (since the conditions were satisfied for all nameservers).
wait_for_txt
> wait_for_txt: fix empty nameserver bug

- changelogs/fragments/fetch_url-devel.yml
- plugins/module_utils/http.py
There was a breaking change in ansible-core's devel branch (see https://github.com/ansible/ansible/pull/76314 for details). This makes this collection's code work with the latest version, and all older ansible-core/ansible-base/Ansible 2.9 versions.
HTTP API helper module utils
> Fix compatibility to fetch_url change in ansible-core devel

- plugins/doc_fragments/hosttech.py
Fix a typo in the `hosttech_password` option description, where it says one also needs to provide `hosttech_password` instead of `hosttech_username`.
hosttech
```paste below
```
> Fix typo in hosttech_password option description

- plugins/doc_fragments/filters.py
- plugins/filter/get_public_suffix.yml
- plugins/filter/get_registrable_domain.yml
- plugins/filter/remove_public_suffix.yml
- plugins/filter/remove_registrable_domain.yml
- tests/sanity/extra/no-unwanted-files.py
Add filter documentation using the new sidecar docs feature for ansible-core 2.13. Rendered with https://github.com/ansible-community/antsibull-docs/pull/6 to: https://ansible.fontein.de/collections/community/dns/index.html#filter-plugins
filter plugin documentation
> Add filter documentation

- tests/unit/requirements.txt
The Python 3.11 unit tests currently fail: https://github.com/ansible-collections/community.dns/runs/6501315889?check_suite_focus=true
CI
> CI: lxml 4.8.0 doesn't work with Python 3.11, and 4.9.0 hasn't been released yet

- changelogs/fragments/105-wait_for_txt-improve-error-msg.yml
- plugins/module_utils/resolver.py
- tests/unit/plugins/module_utils/test_resolver.py
- tests/unit/plugins/modules/test_wait_for_txt.py
Improve error messages for DNS errors so that it is clear which query was made to which server when that error was obtained.
wait_for_txt
> wait_for_txt: improve error messages

- changelogs/fragments/action_groups.yml
- changelogs/fragments/wait_for_txt-check_mode.yml
- docs/docsite/rst/hetzner_guide.rst
- docs/docsite/rst/hosttech_guide.rst
- meta/runtime.yml
- plugins/doc_fragments/attributes.py
- plugins/doc_fragments/module_record.py
- plugins/doc_fragments/module_record_info.py
- plugins/doc_fragments/module_record_set.py
- plugins/doc_fragments/module_record_set_info.py
- plugins/doc_fragments/module_record_sets.py
- plugins/doc_fragments/module_zone_info.py
- plugins/modules/hetzner_dns_record.py
- plugins/modules/hetzner_dns_record_info.py
- plugins/modules/hetzner_dns_record_set.py
- plugins/modules/hetzner_dns_record_set_info.py
- plugins/modules/hetzner_dns_record_sets.py
- plugins/modules/hetzner_dns_zone_info.py
- plugins/modules/hosttech_dns_record.py
- plugins/modules/hosttech_dns_record_info.py
- plugins/modules/hosttech_dns_record_set.py
- plugins/modules/hosttech_dns_record_set_info.py
- plugins/modules/hosttech_dns_record_sets.py
- plugins/modules/hosttech_dns_zone_info.py
- plugins/modules/wait_for_txt.py
Add `community.dns.hetzner` and `community.dns.hosttech` action groups.
Uses attributes to document module capabilities.
The `wait_for_txt` module was not maked as `supports_check_mode=True`. Since it does not make any change, this is clearly an oversight and is now fixed.
all modules
> Add `hetzner` and `hosttech` action groups; use attributes to document module capabilities; support check mode for wait_for_txt

- changelogs/fragments/121-wait_for_txt-ipv6.yml
- plugins/module_utils/resolver.py
- tests/unit/plugins/module_utils/test_resolver.py
- tests/unit/plugins/modules/test_wait_for_txt.py
Fixes #120.
wait_for_txt
resolver module utils
> wait_for_txt: also retrieve IPv6 addresses of nameservers

- changelogs/fragments/txt-quoting.yml
- plugins/doc_fragments/options.py
- plugins/module_utils/conversion/converter.py
- plugins/module_utils/conversion/txt.py
- plugins/module_utils/hetzner/api.py
- plugins/module_utils/hosttech/api.py
- plugins/module_utils/module/record.py
- plugins/module_utils/module/record_info.py
- plugins/module_utils/module/record_set.py
- plugins/module_utils/module/record_set_info.py
- plugins/module_utils/module/record_sets.py
- plugins/module_utils/options.py
- plugins/module_utils/provider.py
- plugins/plugin_utils/inventory/records.py
- tests/unit/plugins/module_utils/conversion/test_converter.py
- tests/unit/plugins/module_utils/conversion/test_txt.py
- tests/unit/plugins/module_utils/helper.py
- tests/unit/plugins/modules/test_hetzner_dns_record_info.py
- tests/unit/plugins/modules/test_hetzner_dns_record_set.py
- tests/unit/plugins/modules/test_hetzner_dns_record_set_info.py
While working on #133 I noticed that DNSPython (and most of the remainder of the world) uses decimal escape sequences for quoted TXT entries, while the code in community.dns uses octal escape sequences. When talking to the API this makes no difference for the APIs currently implemented in this collection (Hosttech uses decoded strings, and Hetzner uses encoded strings, but with no encoding for Unicode characters). But when the user specifies `txt_transform=quoted` this produces different results depending on the input.
This PR adds a new option `txt_character_encoding` (current default: `octal`) that allows to select this behavior, and allows APIs that use such escape sequences to declare the encoding they use.
The defaults for this option and the API declaration will change from `octal` …
> Add txt_character_encoding option. Prepare to switch to decimal escape sequences in community.dns 3.0.0

- plugins/modules/hosttech_dns_zone_info.py
More boolean normalization done with https://github.com/ansible-community/community-team/issues/60#issuecomment-1456867303.
various
> More true/false normalization

- plugins/modules/wait_for_txt.py
- tests/sanity/extra/extra-docs.json
- tests/sanity/extra/extra-docs.py
Use `antsibull-docs lint-collection-docs --plugin-docs` to do additional documentation validation. This is important if the docs build workflow is no longer there (#6344).
This also ensures that no semantic markup is used. This should be changed once the last Ansible 6.x.y release is out containing this collection; from then on we can (relatively) safely start using semantic markup without defacing the Ansible 7 (or before) documentation.
CI
> Do extra docs validation; explicitly disallow semantic markup in docs

- .github/workflows/ansible-test.yml
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/46
CI
> CI: ansible-core devel drops support for Python 3.5

- docs/docsite/rst/filter_guide.rst
- docs/docsite/rst/hetzner_guide.rst
- docs/docsite/rst/hosttech_guide.rst
- plugins/doc_fragments/filters.py
- plugins/doc_fragments/hetzner.py
- plugins/doc_fragments/hosttech.py
- plugins/doc_fragments/inventory_records.py
- plugins/doc_fragments/module_record.py
- plugins/doc_fragments/module_record_info.py
- plugins/doc_fragments/module_record_set.py
- plugins/doc_fragments/module_record_set_info.py
- plugins/doc_fragments/module_record_sets.py
- plugins/doc_fragments/module_zone_info.py
- plugins/doc_fragments/options.py
- plugins/inventory/hetzner_dns_records.py
- plugins/inventory/hosttech_dns_records.py
- plugins/modules/hetzner_dns_record_info.py
- plugins/modules/hetzner_dns_record_set_info.py
- plugins/modules/hetzner_dns_zone_info.py
- plugins/modules/hosttech_dns_record_info.py
- plugins/modules/hosttech_dns_record_set_info.py
- plugins/modules/hosttech_dns_zone_info.py
- plugins/modules/wait_for_txt.py
- tests/sanity/extra/extra-docs.py
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
- tests/sanity/ignore-2.13.txt
- tests/sanity/ignore-2.14.txt
- tests/sanity/ignore-2.9.txt
Depends on https://github.com/ansible/ansible/pull/74937 and ~~https://github.com/ansible-community/antsibull/pull/281~~ https://github.com/ansible-community/antsibull-docs/pull/4.
The result can be seen here:
- https://ansible.fontein.de/collections/community/dns/hosttech_dns_records_module.html#synopsis for `O(ignore=true)` in RST;
- https://ansible.fontein.de/collections/community/dns/hosttech_dns_record_info_module.html#return-sets for `O(what=single_record)` in HTML;
- https://ansible.fontein.de/collections/community/dns/hosttech_dns_records_module.html#parameter-records/prefix for simple `O()` and `V()` usages;
- https://ansible.fontein.de/collections/community/general/dependent_lookup.html#parameter-_raw for `P(ansible.builtin.dict2items#filter)` in HTML;
extra …
> Use semantic markup

- .github/workflows/ansible-test.yml
- tests/unit/replace-requirements.sh
- tests/unit/requirements-stable-2.10.txt
- tests/unit/requirements-stable-2.9.txt
dnspython 2.4 broke unit tests on Python 3.8 for ansible-base 2.10.
unit tests
> Fix CI for ansible-base 2.10 and Ansible 2.9

- plugins/modules/hetzner_dns_record_set.py
`ttl: 3600` isn't allowed by Hetzner and will result in `422 Unprocessable Entity: format: invalid CAA string;`, using `null` will use Hetzners default value, so it should always work.
Also added quotes to the values.
community.dns.hetzner_dns_record_set
> Fixed CAA example

- plugins/module_utils/dnspython_records.py
- plugins/modules/nameserver_info.py
- plugins/modules/nameserver_record_info.py
- plugins/modules/wait_for_txt.py
- tests/unit/plugins/module_utils/test_dnspython_records.py
- tests/unit/plugins/modules/test_nameserver_info.py
- tests/unit/plugins/modules/test_nameserver_record_info.py
Adds two modules that allow to figure out all nameservers responsible for a DNS record (nameserver_info), and querying these nameservers for all records of a type (nameserver_record_info).
nameserver_info
> Add nameserver_info and nameserver_record_info modules

- changelogs/fragments/172-nameserver_record_info.yml
- plugins/modules/nameserver_record_info.py
- tests/unit/plugins/modules/test_nameserver_record_info.py
> nameserver_record_info: fix crash when more than one record is retrieved

- changelogs/fragments/168-custom-dns-server.yml
- plugins/module_utils/resolver.py
- plugins/modules/nameserver_info.py
- plugins/modules/nameserver_record_info.py
- tests/integration/targets/nameserver_info/tasks/main.yml
- tests/integration/targets/nameserver_record_info/tasks/main.yml
This merge request introduces the ability to specify custom DNS servers for resolving nameserver information in the nameserver_info module. It includes enhancements to the ResolveDirectlyFromNameServers class to handle custom server addresses and updates the nameserver_info module to accept a new 'servers' parameter.
community.dns.nameserver_info
> Introduce server specification in nameserver_info module

- changelogs/fragments/168-custom-dns-server.yml
- changelogs/fragments/178-wait_for_txt-server.yml
- plugins/lookup/lookup.py
- plugins/lookup/lookup_as_dict.py
- plugins/modules/nameserver_info.py
- plugins/modules/nameserver_record_info.py
- plugins/modules/wait_for_txt.py
- tests/integration/targets/nameserver_info/tasks/main.yml
- tests/integration/targets/nameserver_record_info/tasks/main.yml
Update #168 to use the same parameter names as for the lookup plugins. Also add the new `server` parameter to wait_for_txt.
CC @hakong
nameserver_info
wait_for_txt
> Rename 'servers' to 'server' for nameserver_*info; add 'server' parameter to wait_for_txt

- changelogs/fragments/181-inventory-filters.yml
- plugins/doc_fragments/hetzner.py
- plugins/doc_fragments/hosttech.py
- plugins/doc_fragments/inventory_records.py
- plugins/inventory/hetzner_dns_records.py
- plugins/inventory/hosttech_dns_records.py
- plugins/plugin_utils/inventory/records.py
- update-docs-fragments.py
This allows to re-use `filters` for the functionality provided by [community.library_inventory_filtering_v1](https://github.com/ansible-collections/community.library_inventory_filtering/) in the next major release.
> Inventory plugins: rename filters to simple_filters

- changelogs/fragments/191-txt-quoting.yml
- plugins/module_utils/conversion/txt.py
- tests/unit/plugins/module_utils/conversion/test_txt.py
> TXT encoding: avoid breaking up quoting of double quotes and backslashes

- tests/unit/requirements-stable-2.10.txt
Ref: https://github.com/ansible-collections/community.dns/actions/runs/8503870587/job/23292353671
unit test requirements
> CI: restrict lxml to < 5.2.0 for ansible-base 2.10 unit tests

- docs/docsite/config.yml
Uses https://github.com/ansible-community/antsibull-docs/pull/267 to render changelog.
I had to add e4cd0ec9c47362c26deac2df99aa5973b7d41bac to `main` first so that my branch is used.
docsite
> Add changelog to docsite

- .github/workflows/ansible-test.yml
- .github/workflows/ee.yml
- .github/workflows/extra-tests.yml
- README.md
- changelogs/fragments/3.0.0.yml
- docs/docsite/rst/hetzner_guide.rst
- galaxy.yml
- meta/runtime.yml
- plugins/doc_fragments/inventory_records.py
- plugins/doc_fragments/options.py
- plugins/inventory/hetzner_dns_records.py
- plugins/inventory/hosttech_dns_records.py
- plugins/module_utils/conversion/converter.py
- plugins/module_utils/options.py
- plugins/module_utils/provider.py
- plugins/modules/hetzner_dns_record.py
- plugins/modules/hetzner_dns_record_set.py
- plugins/modules/hosttech_dns_records.py
- plugins/plugin_utils/inventory/records.py
- tests/unit/plugins/inventory/test_hetzner_dns_records.py
- tests/unit/plugins/inventory/test_hosttech_dns_records.py
- tests/unit/plugins/modules/test_hetzner_dns_record_set_info.py
- Bump version to 3.0.0.
- Remove deprecated features, implement breaking changes.
- Remove `filters` alias of `simple_filters` option for inventory plugins.
- Add new `community.library_inventory_filtering_v1` collection dependency and use it to implement `filters` option for inventory plugins.
various
> [3.0.0] Prepare new major release: remove deprecations, add community.library_inventory_filtering_v1 dependency, add new filter option

- plugins/filter/reverse_pointer.py
- plugins/lookup/reverse_lookup.py
- tests/integration/targets/filter_reverse_pointer/aliases
- tests/integration/targets/filter_reverse_pointer/tasks/main.yml
- tests/integration/targets/lookup_reverse_lookup/aliases
- tests/integration/targets/lookup_reverse_lookup/tasks/main.yml
Add plugins for helping with reverse lookups:
1. A filter to convert IP addresses into DNS names for using with regular lookup plugins;
2. A reverse lookup plugin which does the whole thing in one step.
Fixes #227.
reverse_pointer filter
> Add reverse_pointer filter and reverse_lookup lookup

- plugins/doc_fragments/attributes.py
- plugins/doc_fragments/module_record.py
- plugins/doc_fragments/module_record_info.py
- plugins/doc_fragments/module_record_set.py
- plugins/doc_fragments/module_record_set_info.py
- plugins/doc_fragments/module_record_sets.py
- plugins/doc_fragments/module_zone_info.py
- plugins/modules/hetzner_dns_record_info.py
- plugins/modules/hetzner_dns_record_set_info.py
- plugins/modules/hetzner_dns_zone_info.py
- plugins/modules/hosttech_dns_record_info.py
- plugins/modules/hosttech_dns_record_set_info.py
- plugins/modules/hosttech_dns_zone_info.py
- plugins/modules/nameserver_info.py
- plugins/modules/nameserver_record_info.py
- plugins/modules/wait_for_txt.py
Adds a new attribute `idempotent` for module documentation, which states whether (resp. under which circumstances) the module is idempotent.
Related PRs:
- https://github.com/ansible-collections/community.crypto/pull/833
- https://github.com/ansible-collections/community.docker/pull/1022
- https://github.com/ansible-collections/community.hrobot/pull/132
- https://github.com/ansible-collections/community.routeros/pull/337
- https://github.com/ansible-collections/community.sops/pull/217
module documentation
> Add 'idempotent' attribute

- changelogs/fragments/265-lookup-all.yml
- plugins/lookup/lookup.py
- plugins/lookup/lookup_as_dict.py
Fixes #264.
lookup
lookup_as_dict
> lookup plugins: remove type=ALL which never worked

- plugins/modules/hetzner_dns_record.py
- Adding an A record for `www.example.com` using the `prefix` parameter with the `community.dns.hetzner_dns_record` module.
community.dns.hetzner_dns_record
> Add Hetzner DNS A record using prefix parameter

- changelogs/fragments/280-deprecations.yml
- plugins/plugin_utils/inventory/records.py
- plugins/plugin_utils/unsafe.py
ansible.module_utils._text and ansible.module_utils.common._collections_compat have been deprecated.
various
> ansible-core 2.20: avoid deprecated functionality
