.github/workflows/check-psl.yml
MPL
README.md
changelogs/fragments/domain_suffix.yml
galaxy.yml
plugins/filter/domain_suffix.py
plugins/plugin_utils/public_suffix.py
plugins/public_suffix_list.dat
tests/integration/targets/filter_domain_suffix/aliases
tests/integration/targets/filter_domain_suffix/tasks/main.yml
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.9.txt
tests/unit/plugins/plugin_utils/test_public_suffix.py
update-psl.sh

Migrated from [felixfontein.tools](https://ansible.fontein.de/collections/felixfontein/tools/).
This PR is a bit special since some of the materials added here are licensed under MPL (Mozilla Public License, v. 2.0), namely the [public suffix list](https://publicsuffix.org/).
- New Plugin Pull Request
get_public_suffix
get_registrable_domain
remove_public_suffix
remove_registrable_domain

Add DNS filters

---

changelogs/fragments/14-hosttech-json-rate-limiting.yml
plugins/module_utils/hosttech/json_api.py
tests/unit/plugins/module_utils/hosttech/test_json_api.py
tests/unit/plugins/modules/test_hosttech_dns_record_info.py

Adds basic rate limiting handling for Hosttech's JSON API.
hosttech_dns_*

Hosttech JSON API: Implement rate limit handling

---

plugins/doc_fragments/module_records.py
plugins/module_utils/hosttech/json_api.py
plugins/module_utils/hosttech/wsdl_api.py
plugins/module_utils/module/record.py
plugins/module_utils/module/record_info.py
plugins/module_utils/module/records.py
plugins/module_utils/record.py
plugins/module_utils/zone_record_api.py
plugins/modules/hosttech_dns_records.py
tests/unit/plugins/modules/helper.py
tests/unit/plugins/modules/test_hosttech_dns_record.py
tests/unit/plugins/modules/test_hosttech_dns_records.py

Improve API, add new bulk sync module for all zone records.
hosttech DNS modules

Improve API, add new bulk sync module for all zone records

---

.github/workflows/ansible-test.yml

See https://github.com/ansible-collections/overview/issues/45#issuecomment-836847770
CI

Update Python versions for integration tests: add Python 3.10

---

.github/workflows/ansible-test.yml
.github/workflows/extra-tests.yml
tests/sanity/extra/extra-docs.json
tests/sanity/extra/extra-docs.py
tests/sanity/extra/no-unwanted-files.json
tests/sanity/extra/no-unwanted-files.py

Adds extra docs tests.
- CI Pull Request
CI

Extra docs tests

---

changelogs/fragments/26-refactoring.yml
galaxy.yml
plugins/doc_fragments/hosttech.py
plugins/module_utils/hosttech/api.py
plugins/module_utils/hosttech/json_api.py
plugins/module_utils/json_api_helper.py
plugins/module_utils/zone_record_api.py
tests/unit/plugins/module_utils/hosttech/test_json_api.py
tests/unit/plugins/module_utils/test_json_api_helper.py
tests/unit/plugins/modules/test_hosttech_dns_record.py
tests/unit/plugins/modules/test_hosttech_dns_record_info.py
tests/unit/plugins/modules/test_hosttech_dns_records.py
tests/unit/plugins/modules/test_hosttech_dns_zone_info.py

Refactoring some code in preparation of adding Hetzner modules.
common code

Refactoring

---

changelogs/fragments/28-record-diff.yml
plugins/module_utils/module/record.py
tests/unit/plugins/modules/test_hosttech_dns_record.py

Subset of #27.
hosttech_dns_record

record modules: also return diff when changed == false.

---

changelogs/fragments/29-caa-records-quoting.yml
changelogs/fragments/30-caa-records-quoting.yml
plugins/module_utils/hosttech/json_api.py
tests/unit/plugins/module_utils/hosttech/test_json_api.py
tests/unit/plugins/modules/test_hosttech_dns_record.py
tests/unit/plugins/modules/test_hosttech_dns_records.py

Value should have quotes.
hosttech_dns_*

Fix CAA record handling for Hosttech JSON API

---

tests/integration/targets/hetzner/aliases
tests/integration/targets/hosttech/aliases
tests/integration/targets/required_module_params/aliases
tests/integration/targets/required_module_params/tasks/main.yml

Basic integration tests for all modules. Just run the modules without any arguments and see that all required parameters are mentioned.
all modules

Add more tests

---

changelogs/fragments/37-module-option-provider.yml
plugins/doc_fragments/hetzner.py
plugins/doc_fragments/hosttech.py
plugins/doc_fragments/inventory_records.py
plugins/inventory/hetzner_dns_records.py
plugins/inventory/hosttech_dns_records.py
plugins/module_utils/argspec.py
plugins/module_utils/hetzner/api.py
plugins/module_utils/hosttech/api.py
plugins/modules/hetzner_dns_record.py
plugins/modules/hetzner_dns_record_info.py
plugins/modules/hetzner_dns_record_set.py
plugins/modules/hetzner_dns_record_sets.py
plugins/modules/hetzner_dns_zone_info.py
plugins/modules/hosttech_dns_record.py
plugins/modules/hosttech_dns_record_info.py
plugins/modules/hosttech_dns_record_set.py
plugins/modules/hosttech_dns_record_sets.py
plugins/modules/hosttech_dns_zone_info.py
plugins/plugin_utils/inventory/records.py
tests/unit/plugins/inventory/test_hetzner_dns_records.py
tests/unit/plugins/inventory/test_hosttech_dns_records.py
tests/unit/plugins/module_utils/hosttech/test_api.py

Add an inventory plugin similar to the one from markuman.hetzner_dns.
hetzner_dns_records
hosttech_dns_records

Add inventory plugins

---

docs/docsite/extra-docs.yml
docs/docsite/rst/filter_guide.rst
docs/docsite/rst/hetzner_guide.rst
docs/docsite/rst/hosttech_guide.rst
plugins/modules/hetzner_dns_zone_info.py

Add a guide to the Hetzner modules, including a migration guide.
The inventory plugin isn't documented yet; it's also missing in the HostTech guide. I'll work on that later.
Hetzner modules and plugins

Add Hetzner docs

---

changelogs/fragments/45-cleanup.yml
plugins/inventory/hetzner_dns_records.py
plugins/inventory/hosttech_dns_records.py
plugins/module_utils/hetzner/api.py
plugins/module_utils/json_api_helper.py
plugins/module_utils/module/record_info.py
plugins/module_utils/module/record_sets.py
plugins/module_utils/module/zone_info.py
plugins/module_utils/wsdl.py
plugins/plugin_utils/inventory/records.py

Remove unnecessary imports and assignments. See https://github.com/ansible-collections/ansible-inclusion/discussions/22#discussioncomment-1061021.
Python code

Clean up code

---

plugins/modules/hetzner_dns_record_info.py
plugins/modules/hosttech_dns_record_info.py

Properly documents the `ttls` return value.
hetzner_dns_record_info
hosttech_dns_record_info

Document 'ttls' return value

---

README.md
docs/docsite/rst/hetzner_guide.rst
docs/docsite/rst/hosttech_guide.rst

So far they weren't mentioned there at all.
README
docsite

Mention the inventory plugins in the README and guides

---

docs/docsite/rst/hetzner_guide.rst
docs/docsite/rst/hosttech_guide.rst
plugins/modules/hetzner_dns_record.py
plugins/modules/hosttech_dns_record.py

Inform users on record_set modules

---

changelogs/fragments/66-wait_for_txt.yml
plugins/modules/wait_for_txt.py
tests/integration/targets/wait_for_txt/tasks/main.yml
tests/unit/plugins/modules/test_wait_for_txt.py

Bug currently exposed by CI.
wait_for_txt

wait_for_txt: fix handling of too long TXT entries

---

plugins/inventory/hetzner_dns_records.py
plugins/inventory/hosttech_dns_records.py

These shouldn't be there according to https://github.com/ansible/ansible/issues/71795.

Remove unnecessary fields

---

docs/docsite/rst/hetzner_guide.rst
docs/docsite/rst/hosttech_guide.rst

Fix module name in scenario guides.
scenario guides

Fix module name in docs

---

docs/docsite/links.yml

Adds docs/docsite/links.yml file as suggested here: https://gist.github.com/felixfontein/18b1763ca2a5320808225c4121b50791
docs/docsite/links.yml

Add links.yml file

---

.github/workflows/ansible-test.yml
README.md
tests/sanity/ignore-2.14.txt

stable-2.13 has been branched. Add it to CI.
CI

Add stable-2.13 to CI

---

plugins/modules/hetzner_dns_record.py
plugins/modules/hetzner_dns_zone_info.py
plugins/modules/hosttech_dns_record.py
plugins/modules/hosttech_dns_zone_info.py

Fix examples

---

.github/workflows/ansible-test.yml
.github/workflows/check-psl.yml
.github/workflows/ee.yml
.github/workflows/extra-tests.yml

Spread out nightly CI run times a bit.
CI

Schedule nightly CI at 4:30

---

.github/workflows/ansible-test.yml
.github/workflows/check-psl.yml
.github/workflows/extra-tests.yml

Backport of #95 to stable-1.
CI

[stable-1] Schedule nightly CI at 4:30

---

.github/workflows/ansible-test.yml

CI matrix: ansible-core's devel version supports Python 3.11

---

changelogs/fragments/106-inventory-templating.yml
plugins/doc_fragments/inventory_records.py
plugins/inventory/hetzner_dns_records.py
plugins/inventory/hosttech_dns_records.py
plugins/module_utils/provider.py
plugins/plugin_utils/inventory/records.py
plugins/plugin_utils/templated_options.py
tests/unit/plugins/inventory/test_hetzner_dns_records.py
tests/unit/plugins/inventory/test_hosttech_dns_records.py
tests/unit/plugins/module_utils/test_provider.py

This makes it possible to extract them from a vault, from sops, from the environment, or anywhere else.
hetzner_dns_records inventory plugin
hosttech_dns_records inventory plugin

Allow to template some of the inventory plugin options

---

.github/workflows/reuse.yml
.reuse/dep5
CHANGELOG.rst.license
README.md
changelogs/changelog.yaml.license
changelogs/fragments/licenses.yml
plugins/public_suffix_list.dat
plugins/public_suffix_list.dat.license
tests/sanity/extra/extra-docs.json.license
tests/sanity/extra/licenses.json.license
tests/sanity/extra/licenses.py
tests/sanity/extra/licenses.py.license
tests/sanity/extra/no-unwanted-files.json.license
tests/sanity/extra/update-docs-fragments.json.license
tests/sanity/ignore-2.10.txt.license
tests/sanity/ignore-2.11.txt.license
tests/sanity/ignore-2.12.txt.license
tests/sanity/ignore-2.13.txt.license
tests/sanity/ignore-2.14.txt.license
tests/sanity/ignore-2.9.txt.license
update-psl.sh

Everything except changelog/fragments/ is now reuse conformant (https://reuse.software/spec/).
CC @gotmax23
licensing

Make reuse conformant

---

tests/ee/roles/wait_for_txt/tasks/main.yml
tests/integration/targets/wait_for_txt/tasks/main.yml

The nightly tests have been randomly failing for some days now. Maybe a larger timeout fixes them?
wait_for_txt tests

Increase test timeouts

---

README.md

Copied and slightly adjusted from community.hashi_vault :) CC @briantist 
README.md

README: reference various types of docs

---

docs/docsite/rst/filter_guide.rst

Directly reference filters

---

tests/sanity/extra/update-docs-fragments.py
tests/unit/plugins/inventory/test_hetzner_dns_records.py
tests/unit/plugins/inventory/test_hosttech_dns_records.py
tests/unit/plugins/module_utils/conversion/test_txt.py
tests/unit/plugins/module_utils/hetzner/test_api.py
tests/unit/plugins/module_utils/hosttech/test_api.py
tests/unit/plugins/module_utils/hosttech/test_json_api.py
tests/unit/plugins/module_utils/module/test__utils.py
tests/unit/plugins/module_utils/test_json_api_helper.py
tests/unit/plugins/module_utils/test_record.py
tests/unit/plugins/module_utils/test_zone.py

Ref: https://github.com/ansible-collections/news-for-maintainers/issues/34
tests

Remove unnecessary test imports

---

tests/unit/plugins/modules/test_hetzner_dns_record.py
tests/unit/plugins/modules/test_hetzner_dns_record_info.py
tests/unit/plugins/modules/test_hetzner_dns_record_set.py
tests/unit/plugins/modules/test_hetzner_dns_record_set_info.py
tests/unit/plugins/modules/test_hetzner_dns_record_sets.py
tests/unit/plugins/modules/test_hetzner_dns_zone_info.py
tests/unit/plugins/modules/test_hosttech_dns_record.py
tests/unit/plugins/modules/test_hosttech_dns_record_info.py
tests/unit/plugins/modules/test_hosttech_dns_record_set.py
tests/unit/plugins/modules/test_hosttech_dns_record_set_info.py
tests/unit/plugins/modules/test_hosttech_dns_record_sets.py
tests/unit/plugins/modules/test_hosttech_dns_zone_info.py

Ignore more unnecessary import warnings

---

tests/integration/targets/hetzner/tasks/record-sets.yml
tests/integration/targets/hetzner/tasks/records.yml

Continue yes/no → true/false translations.
various

Normalize bools in tests

---

plugins/modules/hosttech_dns_record_set.py

Equivalent of #153.
hosttech_dns_record_set

Fix CAA example for hosttech module

---

plugins/module_utils/resolver.py
plugins/modules/nameserver_info.py
plugins/modules/nameserver_record_info.py
plugins/modules/wait_for_txt.py
tests/unit/plugins/module_utils/test_resolver.py

Moved out from #155.
- Refactor Pull Request
wait_for_txt
nameserver_info

Refactor requirement and error handling code

---

changelogs/fragments/158-resolver.yml
plugins/module_utils/resolver.py
tests/unit/plugins/module_utils/resolver_helper.py

Improve error handling, and use EDNS.
Extracted from #155.
resolver module utils

Improve error handling, and use EDNS

---

changelogs/fragments/159-servfail.yml
plugins/module_utils/resolver.py
plugins/modules/nameserver_info.py
plugins/modules/nameserver_record_info.py
plugins/modules/wait_for_txt.py
tests/unit/plugins/module_utils/test_resolver.py

Extracted and extended from #155.
Also exposes this in the modules using the resolver module util.
resolver module util
nameserver_info module
nameserver_record_info module
wait_for_txt module

Allow to retry on SERVFAIL

---

.github/workflows/ansible-test.yml
plugins/lookup/lookup.py
plugins/lookup/lookup_as_dict.py
plugins/module_utils/ips.py
plugins/module_utils/resolver.py
plugins/plugin_utils/ips.py
plugins/plugin_utils/resolver.py
tests/ee/roles/wait_for_txt/tasks/main.yml
tests/integration/requirements-stable-2.10.txt
tests/integration/requirements-stable-2.9.txt
tests/integration/targets/lookup_lookup/aliases
tests/integration/targets/lookup_lookup/tasks/main.yml
tests/integration/targets/lookup_lookup_as_dict/aliases
tests/integration/targets/lookup_lookup_as_dict/tasks/main.yml
tests/integration/targets/wait_for_txt/tasks/main.yml
tests/unit/plugins/lookup/test_lookup.py
tests/unit/plugins/lookup/test_lookup_as_dict.py
tests/unit/plugins/module_utils/test_ips.py
tests/unit/plugins/plugin_utils/test_ips.py
tests/unit/plugins/plugin_utils/test_resolver.py
tests/unit/requirements-stable-2.10.txt
tests/unit/requirements-stable-2.9.txt
tests/unit/requirements.txt

These are similar to community.general.dig. Instead of having a boolean parameter which determines the kind of output, I decided to create two distinct lookups so that each has its properly defined output.
lookup
lookup_as_dict

Add lookup and lookup_as_dict lookup plugins

---

plugins/lookup/lookup.py
plugins/lookup/lookup_as_dict.py

lookup plugins: improve documentation to mention query() instead of lookup()

---

changelogs/fragments/165-url.yml
plugins/module_utils/http.py

Ref: https://github.com/ansible/ansible/commit/92d2c66db2eecd0f5e26e6f49589dbcdb4612618
http module utils

Make compatible with current ansible-core devel

---

CHANGELOG.rst
changelogs/changelog.yaml
docs/docsite/rst/filter_guide.rst
docs/docsite/rst/hetzner_guide.rst
docs/docsite/rst/hosttech_guide.rst
plugins/lookup/lookup_as_dict.py
plugins/module_utils/zone_record_helpers.py
plugins/modules/nameserver_record_info.py

Fix typos, improve markup.
various

Fix typos, improve markup

---

README.md

Ref: https://github.com/ansible-collections/community.general/issues/7619#issuecomment-1829657685
README

Mention lookup plugins in the README

---

changelogs/fragments/177-ns-lookup-nxdomain.yml
plugins/module_utils/resolver.py
tests/integration/targets/nameserver_info/tasks/main.yml
tests/unit/plugins/module_utils/test_resolver.py
tests/unit/plugins/modules/test_nameserver_info.py
tests/unit/plugins/modules/test_nameserver_record_info.py
tests/unit/plugins/modules/test_wait_for_txt.py

Fixes #170.
Closes #174.
nameserver resolver

When looking up nameservers for a domain, do not treat NXDOMAIN as a fatal error

---

.github/workflows/import-galaxy.yml

Backport of #179 to stable-1.
CI

[stable-1] Use import galaxy workflow from ansible-collections/community.docker#754

---

changelogs/fragments/inventory-rce.yml
plugins/plugin_utils/inventory/records.py
tests/unit/plugins/inventory/test_hetzner_dns_records.py
tests/unit/plugins/inventory/test_hosttech_dns_records.py

Fixing a potential RCE when using the inventory plugins.
Ref: https://www.die-welt.net/2024/03/remote-code-execution-in-ansible-dynamic-inventory-plugins/
Ref: https://forum.ansible.com/t/remote-code-execution-in-ansible-dynamic-inventory-plugins/4332/3

Prevent RCE via inventory plugins

---

.github/workflows/ansible-test.yml

Ref: https://forum.ansible.com/t/ansible-core-devel-drops-support-for-python-3-7/4736
CI

CI: ansible-core devel dropped support for Python 3.7

---

changelogs/fragments/197-unsafe.yml
plugins/plugin_utils/inventory/records.py
plugins/plugin_utils/unsafe.py
tests/unit/plugins/inventory/test_hetzner_dns_records.py
tests/unit/plugins/inventory/test_hosttech_dns_records.py

Ref: https://github.com/ansible-collections/community.general/issues/8212.

inventory plugins: make wrapping variables as unsafe smarter to avoid triggering an AWX bug

---

README.md
docs/docsite/rst/filter_guide.rst
plugins/filter/quote_txt.yml
plugins/filter/txt.py
plugins/filter/unquote_txt.yml
tests/integration/targets/filter_txt/aliases
tests/integration/targets/filter_txt/tasks/main.yml

Adds filters `quote_txt` and `unquote_txt` for working with TXT records.
Ref: https://github.com/ansible-collections/community.general/pull/8227
quote_txt
unquote_txt

Add quote_txt and unquote_txt filters

---

.github/workflows/ansible-test.yml

Install using ansible-galaxy via git instead of cloning directly.
CI

Install using ansible-galaxy via git instead of cloning directly

---

.github/workflows/ee.yml
.github/workflows/extra-tests.yml

Use `ansible-galaxy collection install` for extra tests. Use Python 3.12 in more places.
CI

Improve CI

---

changelogs/fragments/201-lookup-search.yml
plugins/lookup/lookup.py
plugins/lookup/lookup_as_dict.py
plugins/module_utils/resolver.py
tests/unit/plugins/lookup/test_lookup.py
tests/unit/plugins/lookup/test_lookup_as_dict.py
tests/unit/plugins/module_utils/resolver_helper.py

lookup plugins: add search option; change its default to true

---

plugins/lookup/lookup.py
plugins/lookup/lookup_as_dict.py

[stable-2] lookups: document that the search list is not used, and domains are treated as absolute

---

tests/integration/targets/filter_txt/tasks/main.yml
tests/unit/plugins/plugin_utils/test_unsafe.py

Increase test coverage

---

.github/workflows/check-psl.yml
.github/workflows/ee.yml
.github/workflows/extra-tests.yml
.github/workflows/reuse.yml

Fix some issues in GHA workflows pointed out by zizmor (https://github.com/woodruffw/zizmor).
CI

CI: Fix some issues pointed out by zizmor

---

plugins/filter/reverse_pointer.py
plugins/lookup/reverse_lookup.py
plugins/module_utils/hosttech/wsdl_api.py
plugins/module_utils/http.py
plugins/module_utils/json_api_helper.py
plugins/modules/hetzner_dns_zone_info.py
plugins/modules/wait_for_txt.py
plugins/plugin_utils/ips.py
tests/integration/targets/lookup_reverse_lookup/tasks/main.yml
tests/unit/plugins/inventory/test_hetzner_dns_records.py
tests/unit/plugins/inventory/test_hosttech_dns_records.py
tests/unit/plugins/lookup/test_lookup.py
tests/unit/plugins/lookup/test_reverse_lookup.py
tests/unit/plugins/module_utils/helper.py
tests/unit/plugins/module_utils/resolver_helper.py
tests/unit/plugins/module_utils/test_http.py
tests/unit/plugins/modules/hetzner.py
tests/unit/plugins/modules/hosttech.py
tests/unit/plugins/modules/test_hetzner_dns_record.py
tests/unit/plugins/modules/test_hetzner_dns_record_set.py
tests/unit/plugins/modules/test_hetzner_dns_zone_info.py
tests/unit/plugins/modules/test_hosttech_dns_record.py
tests/unit/plugins/modules/test_hosttech_dns_record_info.py
tests/unit/plugins/modules/test_hosttech_dns_record_set.py
tests/unit/plugins/modules/test_hosttech_dns_record_set_info.py
tests/unit/plugins/modules/test_hosttech_dns_record_sets.py
tests/unit/plugins/modules/test_hosttech_dns_zone_info.py
tests/unit/plugins/modules/test_nameserver_record_info.py
tests/unit/plugins/plugin_utils/test_unsafe.py

Improve code coverage.
various

Increase code coverage

---

tests/integration/targets/nameserver_info/tasks/main.yml
tests/integration/targets/nameserver_record_info/tasks/main.yml

Fix CI (https://github.com/ansible-collections/community.dns/actions/runs/12781601200).
nameserver_info

Fix nameserver_info and nameserver_record_info tests

---

changelogs/fragments/242-linting.yml
plugins/lookup/lookup.py
plugins/lookup/lookup_as_dict.py
plugins/lookup/reverse_lookup.py
plugins/module_utils/conversion/txt.py
plugins/module_utils/dnspython_records.py
plugins/module_utils/hetzner/api.py
plugins/module_utils/hosttech/json_api.py
plugins/module_utils/hosttech/wsdl_api.py
plugins/module_utils/module/_utils.py
plugins/module_utils/module/record.py
plugins/module_utils/module/record_set.py
plugins/module_utils/module/record_sets.py
plugins/module_utils/names.py
plugins/module_utils/record.py
plugins/module_utils/wsdl.py
plugins/module_utils/zone_record_api.py
plugins/modules/wait_for_txt.py
plugins/plugin_utils/inventory/records.py
plugins/plugin_utils/public_suffix.py
plugins/plugin_utils/unsafe.py
tests/unit/plugins/lookup/test_reverse_lookup.py
tests/unit/plugins/module_utils/hetzner/test_api.py
tests/unit/plugins/module_utils/hosttech/test_json_api.py
tests/unit/plugins/module_utils/test_ips.py
tests/unit/plugins/module_utils/test_provider.py
tests/unit/plugins/module_utils/test_resolver.py
tests/unit/plugins/module_utils/test_wsdl.py
tests/unit/plugins/modules/hosttech.py

Uncommented some things in #241 and fixed them.
- Refactoring Pull Request
various

Fix issues pointed out by linters

---

changelogs/fragments/py3-typing.yml
plugins/filter/domain_suffix.py
plugins/filter/reverse_pointer.py
plugins/filter/txt.py
plugins/inventory/hetzner_dns_records.py
plugins/inventory/hosttech_dns_records.py
plugins/lookup/lookup.py
plugins/lookup/lookup_as_dict.py
plugins/lookup/reverse_lookup.py
plugins/plugin_utils/inventory/records.py
plugins/plugin_utils/ips.py
plugins/plugin_utils/public_suffix.py
plugins/plugin_utils/resolver.py
plugins/plugin_utils/templated_options.py
plugins/plugin_utils/unsafe.py
tests/nox-config-mypy.ini
tests/sanity/ignore-2.14.txt
tests/sanity/ignore-2.15.txt
tests/sanity/ignore-2.16.txt
tests/sanity/ignore-2.17.txt
tests/sanity/ignore-2.18.txt
tests/sanity/ignore-2.19.txt

Follow-up to #241.
all Python 3 code

Add typing hints to all Python 3 only code, and parameter type validation for domain_suffix filters

---

tests/integration/targets/filter_txt/tasks/main.yml

Fix filter tests

---

TESTING.md
noxfile.py
tests/nox-config-mypy.ini

Ref: https://nox.thea.codes/en/stable/tutorial.html#running-without-the-nox-command-or-adding-dependencies
- Testing Pull Request
testing infrastructure

Improve nox usage

---

noxfile.py
plugins/lookup/lookup.py
plugins/lookup/lookup_as_dict.py
plugins/lookup/reverse_lookup.py
plugins/module_utils/dnspython_records.py
plugins/module_utils/http.py
plugins/module_utils/json_api_helper.py
plugins/module_utils/zone.py
plugins/module_utils/zone_record_helpers.py
plugins/plugin_utils/ips.py
plugins/plugin_utils/public_suffix.py
plugins/plugin_utils/resolver.py
tests/nox-config-mypy.ini
tests/sanity/ignore-2.14.txt
tests/sanity/ignore-2.15.txt
tests/unit/plugins/inventory/test_hetzner_dns_records.py
tests/unit/plugins/inventory/test_hosttech_dns_records.py
tests/unit/plugins/lookup/test_lookup.py
tests/unit/plugins/lookup/test_lookup_as_dict.py
tests/unit/plugins/lookup/test_reverse_lookup.py
tests/unit/plugins/module_utils/test_json_api_helper.py
tests/unit/plugins/plugin_utils/test_ips.py
tests/unit/plugins/plugin_utils/test_public_suffix.py
tests/unit/plugins/plugin_utils/test_resolver.py
tests/unit/plugins/plugin_utils/test_unsafe.py

Functions without typing hints are not checked by default.
Also we can use type hint comments for Python 2 compatible code.
- Testing Pull Request
typing hints

Improve typing hints

---

tests/unit/plugins/inventory/test_hetzner_dns_records.py
tests/unit/plugins/inventory/test_hosttech_dns_records.py
tests/unit/plugins/modules/test_hetzner_dns_record_set.py
tests/unit/plugins/modules/test_hosttech_dns_record.py
tests/unit/plugins/modules/test_hosttech_dns_record_set.py
tests/unit/plugins/plugin_utils/test_unsafe.py

Extracted from #246, and using new tools just added.
unit tests

Use new tools from community.internal_test_tools.

---

.github/workflows/check-psl.yml
.github/workflows/docs-pr.yml
.github/workflows/docs-push.yml
.github/workflows/ee.yml
galaxy.yml
noxfile.py
plugins/inventory/hosttech_dns_records.py
plugins/modules/hetzner_dns_record_set.py
plugins/modules/hetzner_dns_record_sets.py
plugins/modules/hetzner_dns_zone_info.py
plugins/modules/hosttech_dns_record_set.py
plugins/modules/hosttech_dns_record_sets.py
plugins/modules/wait_for_txt.py
tests/ee/roles/filter_domain_suffix/tasks/main.yml
tests/integration/requirements.yml
tests/integration/targets/filter_domain_suffix/tasks/main.yml
tests/integration/targets/hosttech/tasks/token.yml
tests/integration/targets/hosttech/tasks/username-password.yml
tests/nox-config-yamllint-plugins-examples.yml
tests/nox-config-yamllint-plugins.yml
tests/nox-config-yamllint.yml
tests/unit/requirements.yml

Uses https://github.com/ansible-community/antsibull-nox/pull/42.
CI

Add yamllint to nox

---

.github/workflows/nox.yml
noxfile.py

Uses https://github.com/ansible-community/antsibull-nox/pull/46.
CI

Let antsibull-nox install the dependencies

---

antsibull-nox.toml
noxfile.py

Uses https://github.com/ansible-community/antsibull-nox/pull/50.
CI

Use antsibull-nox config file

---

.github/workflows/nox.yml

Ref: https://github.com/ansible-community/antsibull-nox/pull/53
CI

Simplify shared nox workflow use

---

changelogs/fragments/279-nameserver_record_info-all.yml
plugins/modules/nameserver_record_info.py

Fixes #278. Analogous to #265.

nameserver_record_info: remove ALL type (that never worked)
